import { createComponentRegistryEntry } from "@/src/lib/registry/factories";
import type { ComponentRegistryEntry } from "@/src/lib/registry/types";

export const catalogComponents: ComponentRegistryEntry[] = [
  createComponentRegistryEntry({
    id: "loaders",
    title: "Loaders & Spinners",
    description: "Animated loading indicators for async states and pending screens.",
    category: "General",
    sourcePath: "src/components/ui/loaders.tsx",
    tags: ["loading", "spinner", "feedback"],
  }),
  createComponentRegistryEntry({
    id: "typography",
    title: "Typography",
    description: "Type styles and content patterns for structured text layouts.",
    category: "General",
    tags: ["text", "content", "heading"],
  }),
  createComponentRegistryEntry({
    id: "card",
    title: "Card",
    description: "Flexible container for grouped content, metadata, and actions.",
    category: "Layout",
    sourcePath: "src/components/ui/card.tsx",
    sourceExport: "Card",
    relatedComponents: ["badge", "button"],
  }),
  createComponentRegistryEntry({
    id: "bento-grid",
    title: "Bento Grid",
    description: "Editorial grid layout for feature sections and dashboards.",
    category: "Layout",
    sourcePath: "src/components/ui/bento-grid.tsx",
    sourceExport: "BentoGrid",
  }),
  createComponentRegistryEntry({
    id: "device-mockups",
    title: "Device Mockups",
    description: "Device frames for product previews across desktop and mobile form factors.",
    category: "Layout",
    sourcePath: "src/components/ui/device-mockups.tsx",
  }),
  createComponentRegistryEntry({
    id: "aspect-ratio",
    title: "Aspect Ratio",
    description: "Constrain media and embeds to a fixed aspect ratio.",
    category: "Layout",
    sourcePath: "src/components/ui/primitives.tsx",
    sourceExport: "AspectRatio",
  }),
  createComponentRegistryEntry({
    id: "separator",
    title: "Separator",
    description: "Visual divider for grouping content and actions.",
    category: "Layout",
    sourcePath: "src/components/ui/primitives.tsx",
    sourceExport: "Separator",
  }),
  createComponentRegistryEntry({
    id: "scroll-area",
    title: "Scroll Area",
    description: "Styled scroll container for overflow-heavy content.",
    category: "Layout",
    sourcePath: "src/components/ui/primitives.tsx",
    sourceExport: "ScrollArea",
  }),
  createComponentRegistryEntry({
    id: "input",
    title: "Input",
    description: "Standard text input field for forms and filters.",
    category: "Forms",
    sourcePath: "src/components/ui/input.tsx",
    sourceExport: "Input",
  }),
  createComponentRegistryEntry({
    id: "textarea",
    title: "Textarea",
    description: "Multiline text field for messages, notes, and descriptions.",
    category: "Forms",
    sourcePath: "src/components/ui/textarea.tsx",
    sourceExport: "Textarea",
  }),
  createComponentRegistryEntry({
    id: "checkbox",
    title: "Checkbox",
    description: "Binary input for multi-select and consent flows.",
    category: "Forms",
    sourcePath: "src/components/ui/checkbox.tsx",
    sourceExport: "Checkbox",
  }),
  createComponentRegistryEntry({
    id: "radio-group",
    title: "Radio Group",
    description: "Single-selection input for mutually exclusive choices.",
    category: "Forms",
    sourcePath: "src/components/ui/radio-group.tsx",
    sourceExport: "RadioGroup",
  }),
  createComponentRegistryEntry({
    id: "switch",
    title: "Switch",
    description: "Toggle control for on/off settings.",
    category: "Forms",
    sourcePath: "src/components/ui/switch.tsx",
    sourceExport: "Switch",
  }),
  createComponentRegistryEntry({
    id: "slider",
    title: "Slider",
    description: "Range input for numeric selection and tuning.",
    category: "Forms",
    sourcePath: "src/components/ui/slider.tsx",
    sourceExport: "Slider",
  }),
  createComponentRegistryEntry({
    id: "select",
    title: "Select",
    description: "Dropdown selection menu for predefined options.",
    category: "Forms",
    sourcePath: "src/components/ui/select.tsx",
    sourceExport: "Select",
  }),
  createComponentRegistryEntry({
    id: "combobox",
    title: "Combobox",
    description: "Searchable selection UI for larger option sets.",
    category: "Forms",
    sourcePath: "src/components/ui/combobox.tsx",
    sourceExport: "Combobox",
  }),
  createComponentRegistryEntry({
    id: "input-otp",
    title: "Input OTP",
    description: "Segmented one-time password input for auth flows.",
    category: "Forms",
    sourcePath: "src/components/ui/inputs-advanced.tsx",
    sourceExport: "InputOTP",
  }),
  createComponentRegistryEntry({
    id: "input-tag",
    title: "Input Tag",
    description: "Tag entry input for labels, recipients, and multi-value fields.",
    category: "Forms",
    sourcePath: "src/components/ui/inputs-advanced.tsx",
    sourceExport: "InputTag",
  }),
  createComponentRegistryEntry({
    id: "file-upload",
    title: "File Upload",
    description: "Drag-and-drop upload field for files and attachments.",
    category: "Forms",
    sourcePath: "src/components/ui/inputs-advanced.tsx",
    sourceExport: "FileUpload",
  }),
  createComponentRegistryEntry({
    id: "toggle",
    title: "Toggle",
    description: "Pressed-state control for compact option toggles.",
    category: "Forms",
    sourcePath: "src/components/ui/inputs-advanced.tsx",
    sourceExport: "Toggle",
  }),
  createComponentRegistryEntry({
    id: "markdown-editor",
    title: "Markdown Editor",
    description: "Markdown editor with live preview for content workflows.",
    category: "Forms",
    sourcePath: "src/components/ui/markdown-editor.tsx",
    sourceExport: "MarkdownEditor",
  }),
  createComponentRegistryEntry({
    id: "table",
    title: "Table",
    description: "Standard table primitives for structured data.",
    category: "Data Display",
    sourcePath: "src/components/ui/table.tsx",
    sourceExport: "Table",
  }),
  createComponentRegistryEntry({
    id: "data-table-advanced",
    title: "Data Table Advanced",
    description: "Feature-rich table with sorting, filtering, and large dataset support.",
    category: "Data Display",
    sourcePath: "src/components/ui/data-table-advanced.tsx",
    sourceExport: "DataTableAdvanced",
  }),
  createComponentRegistryEntry({
    id: "charts",
    title: "Charts",
    description: "Composable chart components for visualizing trends and distributions.",
    category: "Data Display",
    sourcePath: "src/components/ui/charts.tsx",
  }),
  createComponentRegistryEntry({
    id: "calendar",
    title: "Calendar",
    description: "Date and schedule UI for picking and browsing dates.",
    category: "Data Display",
    sourcePath: "src/components/ui/calendar.tsx",
    sourceExport: "Calendar",
  }),
  createComponentRegistryEntry({
    id: "timeline",
    title: "Timeline",
    description: "Sequential activity and event display for history-heavy screens.",
    category: "Data Display",
    sourcePath: "src/components/ui/timeline.tsx",
    sourceExport: "Timeline",
  }),
  createComponentRegistryEntry({
    id: "avatar",
    title: "Avatar",
    description: "Profile image primitive with fallback states.",
    category: "Data Display",
    sourcePath: "src/components/ui/avatar.tsx",
    sourceExport: "Avatar",
  }),
  createComponentRegistryEntry({
    id: "stats",
    title: "Stats",
    description: "Metric cards and summary layouts for dashboards.",
    category: "Data Display",
    sourcePath: "src/components/ui/stats.tsx",
  }),
  createComponentRegistryEntry({
    id: "skeleton",
    title: "Skeleton",
    description: "Loading placeholder blocks for content still in flight.",
    category: "Data Display",
    sourcePath: "src/components/ui/skeleton.tsx",
    sourceExport: "Skeleton",
  }),
  createComponentRegistryEntry({
    id: "kanban",
    title: "Kanban",
    description: "Board-style workflow layout for task and pipeline management.",
    category: "Data Display",
    sourcePath: "src/components/ui/kanban.tsx",
    sourceExport: "KanbanBoard",
  }),
  createComponentRegistryEntry({
    id: "pricing",
    title: "Pricing",
    description: "Pricing cards and plan comparison layouts.",
    category: "Data Display",
    sourcePath: "src/components/ui/pricing.tsx",
    sourceExport: "Pricing",
  }),
  createComponentRegistryEntry({
    id: "tabs",
    title: "Tabs",
    description: "Tabbed navigation for switching between related content panels.",
    category: "Navigation",
    sourcePath: "src/components/ui/tabs.tsx",
    sourceExport: "Tabs",
  }),
  createComponentRegistryEntry({
    id: "breadcrumbs",
    title: "Breadcrumbs",
    description: "Hierarchy-based navigation trail for nested pages.",
    category: "Navigation",
    sourcePath: "src/components/ui/navigation.tsx",
    sourceExport: "Breadcrumbs",
  }),
  createComponentRegistryEntry({
    id: "pagination",
    title: "Pagination",
    description: "Paging controls for list and table navigation.",
    category: "Navigation",
    sourcePath: "src/components/ui/navigation.tsx",
    sourceExport: "Pagination",
  }),
  createComponentRegistryEntry({
    id: "navigation-menu",
    title: "Navigation Menu",
    description: "Advanced site navigation menus for headers and mega menus.",
    category: "Navigation",
    sourcePath: "src/components/ui/navigation-advanced.tsx",
    sourceExport: "NavigationMenu",
  }),
  createComponentRegistryEntry({
    id: "menubar",
    title: "Menubar",
    description: "Desktop-style application menu bar.",
    category: "Navigation",
    sourcePath: "src/components/ui/overlay-advanced.tsx",
    sourceExport: "Menubar",
  }),
  createComponentRegistryEntry({
    id: "stepper",
    title: "Stepper",
    description: "Step-based progress indicator for multi-stage flows.",
    category: "Navigation",
    sourcePath: "src/components/ui/stepper.tsx",
    sourceExport: "Stepper",
  }),
  createComponentRegistryEntry({
    id: "alert",
    title: "Alert",
    description: "Inline status and warning messaging.",
    category: "Feedback",
    sourcePath: "src/components/ui/feedback.tsx",
    sourceExport: "Alert",
  }),
  createComponentRegistryEntry({
    id: "progress",
    title: "Progress",
    description: "Progress indicators for uploads, steps, and async work.",
    category: "Feedback",
    sourcePath: "src/components/ui/feedback.tsx",
    sourceExport: "Progress",
  }),
  createComponentRegistryEntry({
    id: "spinner",
    title: "Spinner",
    description: "Compact loading spinner for buttons and small placeholders.",
    category: "Feedback",
    sourcePath: "src/components/ui/spinner.tsx",
    sourceExport: "Spinner",
  }),
  createComponentRegistryEntry({
    id: "toast",
    title: "Toast",
    description: "Transient notification system for success, error, and info messages.",
    category: "Feedback",
    sourcePath: "src/components/ui/toast.tsx",
  }),
  createComponentRegistryEntry({
    id: "tooltip",
    title: "Tooltip",
    description: "Short contextual hint shown on hover or focus.",
    category: "Overlay",
    sourcePath: "src/components/ui/tooltip.tsx",
    sourceExport: "Tooltip",
  }),
  createComponentRegistryEntry({
    id: "popover",
    title: "Popover",
    description: "Floating panel anchored to a trigger element.",
    category: "Overlay",
    sourcePath: "src/components/ui/popover.tsx",
    sourceExport: "Popover",
  }),
  createComponentRegistryEntry({
    id: "dropdown-menu",
    title: "Dropdown Menu",
    description: "Action menu for compact contextual choices.",
    category: "Overlay",
    sourcePath: "src/components/ui/dropdown-menu.tsx",
    sourceExport: "DropdownMenu",
  }),
  createComponentRegistryEntry({
    id: "context-menu",
    title: "Context Menu",
    description: "Right-click menu for contextual actions.",
    category: "Overlay",
    sourcePath: "src/components/ui/overlay-advanced.tsx",
    sourceExport: "ContextMenu",
  }),
  createComponentRegistryEntry({
    id: "hover-card",
    title: "Hover Card",
    description: "Preview card shown on hover for linked entities and metadata.",
    category: "Overlay",
    sourcePath: "src/components/ui/overlay-advanced.tsx",
    sourceExport: "HoverCard",
  }),
  createComponentRegistryEntry({
    id: "sheet",
    title: "Sheet",
    description: "Slide-over panel for secondary flows and contextual tasks.",
    category: "Overlay",
    sourcePath: "src/components/ui/sheet.tsx",
    sourceExport: "Sheet",
  }),
  createComponentRegistryEntry({
    id: "alert-dialog",
    title: "Alert Dialog",
    description: "High-stakes confirmation dialog for destructive actions.",
    category: "Overlay",
    sourcePath: "src/components/ui/alert-dialog.tsx",
    sourceExport: "AlertDialog",
  }),
  createComponentRegistryEntry({
    id: "dialogs",
    title: "Dialogs",
    description: "Modal flows for auth, confirmation, and focused interaction.",
    category: "Overlay",
    sourcePath: "src/components/ui/dialogs.tsx",
  }),
  createComponentRegistryEntry({
    id: "cookies-banner",
    title: "Cookies Banner",
    description: "Consent banner for privacy and cookie preferences.",
    category: "Overlay",
    sourcePath: "src/components/ui/cookies-banner.tsx",
    sourceExport: "CookiesBanner",
  }),
  createComponentRegistryEntry({
    id: "command-palette",
    title: "Command Palette",
    description: "Keyboard-driven search and action launcher.",
    category: "Advanced",
    sourcePath: "src/components/ui/command-palette.tsx",
    sourceExport: "CommandPalette",
  }),
  createComponentRegistryEntry({
    id: "3d-pin",
    title: "3D Pin",
    description: "Interactive 3D hover card for standout links and showcases.",
    category: "Advanced",
    sourcePath: "src/components/ui/3d-pin.tsx",
    sourceExport: "PinContainer",
  }),
  createComponentRegistryEntry({
    id: "hero",
    title: "Hero",
    description: "Landing page hero section for high-impact product messaging.",
    category: "Advanced",
    sourcePath: "src/components/ui/hero.tsx",
    sourceExport: "Hero",
  }),
];
