"use client";

import { useState } from "react";
import { Code2, Copy, Check, X } from "lucide-react";
import type { OpsScheme } from "@/src/setups/ops-schemes";

function generateSchemeCode(scheme: OpsScheme): string {
  const bgMap: Record<string, string> = {
    "space-labs": "#0b1018",
    "smart-farm": "#f6f8f1",
    "engineering-studio": "#111315",
    "architecture-office": "#efece6",
    "creative-agency": "#081324",
    "portfolio-minimal": "#f4f4f2",
    "company-intro": "#f8fafc",
  };
  const fgMap: Record<string, string> = {
    "space-labs": "#ffffff",
    "smart-farm": "#1f2b1f",
    "engineering-studio": "#eceef0",
    "architecture-office": "#282420",
    "creative-agency": "#ffffff",
    "portfolio-minimal": "#1a1a19",
    "company-intro": "#0f172a",
  };
  const accentMap: Record<string, string> = {
    "space-labs": "#3b82f6",
    "smart-farm": "#61855a",
    "engineering-studio": "#6b7280",
    "architecture-office": "#7b6f62",
    "creative-agency": "#06b6d4",
    "portfolio-minimal": "#6f6f6a",
    "company-intro": "#3b82f6",
  };

  const bg = bgMap[scheme.slug] ?? "#ffffff";
  const fg = fgMap[scheme.slug] ?? "#000000";
  const accent = accentMap[scheme.slug] ?? "#3b82f6";

  const pagesStr = scheme.pages.map((p) => `"${p}"`).join(", ");
  const featuresStr = scheme.features.map((f) => `"${f}"`).join(", ");
  const blocksStr = scheme.blocks.map((b) => `"${b}"`).join(",\n    ");

  return `// ${scheme.slug}/page.tsx — ${scheme.title}
// Sector: ${scheme.sector} · Tone: ${scheme.tone}
// Generated by Struct UI OPS Schemes

export default function ${scheme.title.replace(/\s+/g, "")}Page() {
  const pages = [${pagesStr}];
  const features = [${featuresStr}];
  const blocks = [
    ${blocksStr}
  ];

  return (
    <div
      style={{ background: "${bg}", color: "${fg}" }}
      className="min-h-screen font-sans"
    >
      {/* ── Navigation ── */}
      <nav className="fixed inset-x-0 top-0 z-50 flex items-center justify-between px-8 py-4 backdrop-blur-md bg-black/20 border-b border-white/10">
        <span className="text-sm font-semibold tracking-wide">${scheme.title}</span>
        <ul className="hidden md:flex items-center gap-6">
          {pages.map((page) => (
            <li key={page}>
              <a
                href={\`#\${page.toLowerCase().replace(/\\s/g, "-")}\`}
                className="text-xs uppercase tracking-widest opacity-75 hover:opacity-100 transition-opacity"
              >
                {page}
              </a>
            </li>
          ))}
        </ul>
        <a
          href="#contact"
          style={{ background: "${accent}" }}
          className="hidden md:inline-flex text-white text-xs px-4 py-2 hover:opacity-90 transition-opacity"
        >
          Get Started
        </a>
      </nav>

      {/* ── Hero ── */}
      <section id="landing" className="relative min-h-screen flex items-end pb-20 pt-32 px-8 md:px-16 overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: "url('/hero-placeholder.jpg')" }}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-black/20" />
        <div className="relative max-w-4xl space-y-6">
          <p
            style={{ color: "${accent}" }}
            className="text-xs uppercase tracking-[0.22em]"
          >
            ${scheme.sector}
          </p>
          <h1 className="text-5xl md:text-7xl font-semibold leading-[1.05] text-white">
            ${scheme.title}
          </h1>
          <p className="max-w-xl text-base leading-relaxed text-white/80">
            ${scheme.summary}
          </p>
          <div className="flex flex-wrap gap-3 pt-2">
            <a
              href="#services"
              style={{ background: "${accent}" }}
              className="text-white text-sm px-6 py-3 hover:opacity-90 transition-opacity"
            >
              Explore
            </a>
            <a
              href="#contact"
              className="border border-white/30 text-white text-sm px-6 py-3 hover:bg-white/10 transition-colors"
            >
              Contact Us
            </a>
          </div>
        </div>
      </section>

      {/* ── Stats Strip ── */}
      <section className="grid grid-cols-2 md:grid-cols-4 border-b" style={{ borderColor: "rgba(128,128,128,0.2)" }}>
        {[["Years Active", "12+"], ["Projects Done", "340+"], ["Countries", "18"], ["Satisfaction", "98%"]].map(([label, value]) => (
          <div key={label} className="px-8 py-6 border-r" style={{ borderColor: "rgba(128,128,128,0.2)" }}>
            <p className="text-3xl font-semibold" style={{ color: "${accent}" }}>{value}</p>
            <p className="text-xs uppercase tracking-widest mt-1 opacity-60">{label}</p>
          </div>
        ))}
      </section>

      {/* ── Features / Services ── */}
      <section id="services" className="px-8 md:px-16 py-20 space-y-12">
        <div className="max-w-xl space-y-3">
          <p className="text-xs uppercase tracking-widest opacity-50">What We Offer</p>
          <h2 className="text-3xl md:text-4xl font-semibold leading-snug">
            Built for ${scheme.sector} Excellence
          </h2>
        </div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {features.map((feature) => (
            <div
              key={feature}
              className="p-5 border space-y-3"
              style={{ borderColor: "rgba(128,128,128,0.2)" }}
            >
              <div
                className="w-8 h-8 rounded-sm"
                style={{ background: "${accent}", opacity: 0.85 }}
              />
              <p className="text-sm font-medium">{feature}</p>
              <p className="text-xs leading-relaxed opacity-55">
                Delivering measurable results with modern tooling and refined process.
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Blocks / Work ── */}
      <section id="work" className="px-8 md:px-16 py-20 border-t" style={{ borderColor: "rgba(128,128,128,0.15)" }}>
        <div className="flex items-end justify-between mb-10">
          <div className="space-y-2">
            <p className="text-xs uppercase tracking-widest opacity-50">Selected Modules</p>
            <h2 className="text-3xl font-semibold">Core Block System</h2>
          </div>
        </div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {blocks.map((block) => (
            <div
              key={block}
              className="group relative overflow-hidden border p-6 cursor-pointer transition-colors hover:border-opacity-60"
              style={{ borderColor: "rgba(128,128,128,0.2)" }}
            >
              <div
                className="absolute inset-0 opacity-0 group-hover:opacity-5 transition-opacity"
                style={{ background: "${accent}" }}
              />
              <p className="text-sm font-medium leading-snug">{block}</p>
              <p className="mt-2 text-xs opacity-45">Struct UI component</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Testimonial ── */}
      <section
        className="px-8 md:px-16 py-20"
        style={{ background: "${accent}", color: "#ffffff" }}
      >
        <div className="max-w-3xl mx-auto text-center space-y-6">
          <p className="text-3xl md:text-4xl font-semibold leading-snug">
            "The best ${scheme.sector.toLowerCase()} platform we've ever used — fast, reliable, and beautiful."
          </p>
          <div className="space-y-1">
            <p className="text-sm font-medium opacity-90">Alex Morgan</p>
            <p className="text-xs uppercase tracking-widest opacity-65">Director, ${scheme.sector} Corp</p>
          </div>
        </div>
      </section>

      {/* ── Pages Overview ── */}
      <section className="px-8 md:px-16 py-20 space-y-10">
        <div className="space-y-2">
          <p className="text-xs uppercase tracking-widest opacity-50">Site Structure</p>
          <h2 className="text-3xl font-semibold">Page Architecture</h2>
        </div>
        <div className="space-y-0">
          {pages.map((page, index) => (
            <div
              key={page}
              className="flex items-center justify-between py-4 border-b"
              style={{ borderColor: "rgba(128,128,128,0.15)" }}
            >
              <div className="flex items-center gap-4">
                <span className="text-xs opacity-35 w-5">{String(index + 1).padStart(2, "0")}</span>
                <span className="text-sm font-medium">{page}</span>
              </div>
              <span
                className="text-xs uppercase tracking-widest opacity-50"
                style={{ color: "${accent}" }}
              >
                View →
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* ── Contact ── */}
      <section
        id="contact"
        className="px-8 md:px-16 py-24 border-t"
        style={{ borderColor: "rgba(128,128,128,0.15)" }}
      >
        <div className="max-w-2xl mx-auto text-center space-y-8">
          <div className="space-y-3">
            <p className="text-xs uppercase tracking-widest opacity-50">Get In Touch</p>
            <h2 className="text-4xl font-semibold">Start Your Project</h2>
            <p className="text-sm leading-relaxed opacity-65">
              Ready to build something exceptional? We're here to help you bring it to life.
            </p>
          </div>
          <form className="space-y-4 text-left">
            <div className="grid gap-4 sm:grid-cols-2">
              <input
                type="text"
                placeholder="Your Name"
                className="w-full px-4 py-3 text-sm border bg-transparent outline-none focus:ring-1 transition-all"
                style={{ borderColor: "rgba(128,128,128,0.3)" }}
              />
              <input
                type="email"
                placeholder="Email Address"
                className="w-full px-4 py-3 text-sm border bg-transparent outline-none focus:ring-1 transition-all"
                style={{ borderColor: "rgba(128,128,128,0.3)" }}
              />
            </div>
            <textarea
              rows={4}
              placeholder="Tell us about your project..."
              className="w-full px-4 py-3 text-sm border bg-transparent outline-none focus:ring-1 transition-all resize-none"
              style={{ borderColor: "rgba(128,128,128,0.3)" }}
            />
            <button
              type="submit"
              style={{ background: "${accent}" }}
              className="w-full text-white text-sm py-3 hover:opacity-90 transition-opacity"
            >
              Send Message
            </button>
          </form>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer
        className="px-8 md:px-16 py-8 border-t flex items-center justify-between"
        style={{ borderColor: "rgba(128,128,128,0.15)" }}
      >
        <span className="text-xs opacity-40">${scheme.title} © {new Date().getFullYear()}</span>
        <span className="text-xs opacity-40">Built with Struct UI OPS</span>
      </footer>
    </div>
  );
}
`;
}

interface CopySchemeCodeProps {
  scheme: OpsScheme;
}

export function CopySchemeCode({ scheme }: CopySchemeCodeProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const code = generateSchemeCode(scheme);

  function handleCopy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="inline-flex items-center gap-2 border border-white/25 bg-black/40 px-3 py-1.5 text-[11px] uppercase tracking-[0.12em] text-white backdrop-blur-md transition-colors hover:bg-black/55"
      >
        <Code2 className="h-3.5 w-3.5" />
        Copy Code
      </button>

      {open && (
        <div className="fixed inset-0 z-[200] flex items-end justify-end p-4 pointer-events-none md:p-6">
          <div
            className="pointer-events-auto flex max-h-[80vh] w-full max-w-2xl flex-col overflow-hidden border border-white/15 bg-[#0d0d0d] shadow-2xl"
          >
            {/* Header */}
            <div className="flex items-center justify-between border-b border-white/10 px-5 py-3">
              <div className="space-y-0.5">
                <p className="text-[11px] uppercase tracking-[0.14em] text-white/45">
                  {scheme.sector} · {scheme.slug}
                </p>
                <p className="text-sm font-medium text-white">{scheme.title} — page.tsx</p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="inline-flex items-center gap-1.5 border border-white/20 bg-white/8 px-3 py-1.5 text-[11px] uppercase tracking-[0.1em] text-white transition-colors hover:bg-white/15"
                >
                  {copied ? (
                    <>
                      <Check className="h-3 w-3 text-emerald-400" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="h-3 w-3" />
                      Copy
                    </>
                  )}
                </button>
                <button
                  onClick={() => setOpen(false)}
                  className="flex h-7 w-7 items-center justify-center border border-white/15 bg-white/5 text-white/60 transition-colors hover:bg-white/12 hover:text-white"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>

            {/* Code */}
            <div className="overflow-y-auto">
              <pre className="p-5 text-[11px] leading-relaxed text-white/80">
                <code>{code}</code>
              </pre>
            </div>

            {/* Footer */}
            <div className="border-t border-white/10 px-5 py-2.5">
              <p className="text-[10px] uppercase tracking-[0.12em] text-white/30">
                Struct UI OPS · Single-page template · Requires Tailwind CSS
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
